# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dot_Order' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dot_Order
  pod 'Kommunicate'

end
